version: '3'
services:
  cnil-pia-back:
    container_name: LINCnil-pia-back
    build: docker/cnil-pia-back
    restart: always
    environment:
      DATABASE_HOST: 'database'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'somepassword'
      SECRET_KEY_BASE: 'somesecret'
    links:
      - database
    depends_on:
      - database
    ports:
      - 3000:3000

  cnil-pia-front:
    container_name: LINCnil-pia-front
    build: docker/cnil-pia-front
    restart: always
    ports:
      - 0.0.0.0:8080:80

  database:
    container_name: kosmas58-pia-db
    image: library/postgres:12.5
    restart: always
    environment:
      POSTGRES_PASSWORD: 'somepassword'
